website/settings/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, SubmitField, BooleanField, SelectMultipleField, Form, SelectField, FileField, IntegerField, StringField
from wtforms.validators import Email, DataRequired
from wtforms.fields import FieldList, FormField
from flask_wtf.file import FileRequired, FileAllowed


class TanquesForm(FlaskForm):
    id_estacion = SelectMultipleField('Estación', coerce=int)
    id_producto = SelectMultipleField('Producto', coerce=int)
    no_tanque = TextField('Numero tanque', validators=[DataRequired()])
    volumenUtil = TextField('Volumen Util',validators=[DataRequired()])
    volumenFondaje = TextField('Volumen Fondaje',validators=[DataRequired()])
    volumenAgua = TextField('Volumen Agua',validators=[DataRequired()])
    volumenDisponible = TextField('Volumen Disponible',validators=[DataRequired()])
    volumenExtraccion = TextField('Volumen Extraccion',validators=[DataRequired()])
    volumenRecepcion = TextField('Volumen Recepcion',validators=[DataRequired()])
    temperatura = TextField('Temperatura',validators=[DataRequired()])
    activo = BooleanField('Activo:', default=True)
    submit = SubmitField("Guardar")
    
class ProductosForm(FlaskForm):
    nombre = TextField('Nombre comercial', validators=[DataRequired()])
    nombre_corto = TextField('Nombre corto', validators=[DataRequired()])
    claveProducto = TextField('Clave producto', validators=[DataRequired()])
    claveSubProducto = TextField('Clave sub-producto', validators=[DataRequired()])
    composicionOctanajeDeGasolina = TextField('Octanaje', validators=[])
    gasolinaConEtanol = TextField('Gasolina con etanol', validators=[])
    claveProductoPEMEX = TextField('Clave producto PEMEX', validators=[DataRequired()])
    submit = SubmitField("Guardar")
    
class MangueraForm(Form):
    identificadorManguera = TextField('Numero Manguera', validators=[DataRequired()])
    id_producto = SelectField('Producto', coerce=int)
    
    
class DispensariosForm(FlaskForm):
    numeroDispensario = TextField('Numero Dispensario', validators=[DataRequired()])
    id_estacion = SelectField('Estación', coerce=int)
    mangueras = FieldList(FormField(MangueraForm), min_entries = 0)
    submit = SubmitField("Guardar")
    
class EstacionTanquesForm(Form):
    no_tanque = TextField('Numero tanque', validators=[DataRequired()])
    producto = StringField('Producto', render_kw={'readonly': True})
    volumenUtil = StringField('Volumen Util')
    volumenDisponible = StringField('Volumen Disponible')
    

class EstacionForm(FlaskForm):
    nombre = TextField('Estacion', validators=[DataRequired()])
    id_zona = SelectMultipleField('Zona', coerce=int)
    numeroPermisoCRE = TextField('Numero Permiso CRE', validators=[DataRequired()])
    id_empresa = SelectMultipleField('Empresa', coerce=int)
    id_producto = SelectMultipleField('Productos', coerce=int)
    activo = BooleanField('Activo:', default=True)
    ruta = TextField('Ruta SFTP', validators=[DataRequired()])
    claveClientePEMEX = TextField('Clave Cliente Pemex', validators=[DataRequired()])
    claveEstacionServicio = TextField('Clave Estacion Servicio', validators=[DataRequired()])

    # Agregamos validadores para garantizar que se carguen los archivos y que sean de la extensión adecuada
    key_file = FileField('Archivo Key', validators=[FileAllowed(['key'], 'Solo archivos .key permitidos!')])
    cer_file = FileField('Archivo Cer', validators=[FileAllowed(['cer'], 'Solo archivos .cer permitidos!')])
    pem_file = FileField('Archivo Pem', validators=[FileAllowed(['pem'], 'Solo archivos .pem permitidos!')])
    
    noCertificado = TextField('Numero de Certificado')
    certificado_value = TextField('Valor de Certificado')

    tanques = FieldList(FormField(EstacionTanquesForm),min_entries = 0)
    submit = SubmitField("Guardar")
    

website/settings/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2021 - present NovaRet
"""

from flask import Blueprint

blueprint = Blueprint(
    'settings_blueprint',
    __name__,
    url_prefix=''
)

website/settings/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2021 - present NovaRet
"""
from werkzeug.utils import secure_filename
import os
from website import db
from website.settings import blueprint
from flask import render_template, request, jsonify, redirect, url_for, flash, current_app
from flask_login import login_required, current_user
import json
from website.authentication.utils import hash_pass
from website.authentication.models import Usuario, UserSchema, Grupo, GroupSchema
from website.settings.models import Empresa, EmpresaSchema, Version, EstacionSchema, Zona, Estacion, Tanques, Producto, Dispensario, Manguera, estaciones_productos
from website.settings.forms import TanquesForm, ProductosForm, DispensariosForm, MangueraForm, EstacionForm, EstacionTanquesForm
from website.home.utils.gen_pem import GenPem
from website.home.utils.cer_data import CerData
from xml.dom import minidom

@blueprint.route('/usuarios', methods=['GET','PUT'])
@login_required
def users():    
    return render_template('settings/users.html', segment='usersSettings_users')

@blueprint.route('/api_users', methods=['GET'])
@login_required
def api_users():
    usuarios = Usuario.query.filter_by(activo = True).order_by(Usuario.id.asc()).all()
    user_schema = UserSchema(many=True)
    return jsonify(user_schema.dump(usuarios).data)

@blueprint.route('/api_users/update',methods=['PUT'])
@login_required
def api_users_update():
    if int(request.json['grupo']) == 0: 
        response = {'message': 'Grupo no puede ser nulo.'}
        return jsonify(response), 400
    
    # Encripta la contraseña antes de pasarla a la base de datos
    password = hash_pass(request.json['password'])

    args = {
        "username": request.json['username'],
        "email": request.json['email'],
        "id_grupo": int(request.json['grupo']),
        "activo": request.json['activo'],
        "escrito_por": current_user.id,
        "password": password  # Utiliza el valor encriptado de la contraseña
    }
    
    Usuario.query.filter_by(id=request.json['id']).update(args)
    db.session.commit()
    
    response = {'message': f'Usuario {args["username"]} editado con éxito.'}
    return jsonify(response)


@blueprint.route('/api_users/insert', methods=['POST'])
@login_required
def api_users_insert():
    data = request.json
    username = data['username']
    email = data['email']
    grupo_id = data['grupo']
    activo = data['activo']
    password = data['password']  # Asegúrate de que este campo exista en los datos enviados
    creado_por = current_user.id

    # Crea una nueva instancia del modelo Usuario con los datos recibidos
    new_user = Usuario(username=username, email=email, id_grupo=grupo_id, activo=activo, password=str(password),creado_por=creado_por)

    # Agrega el nuevo usuario a la base de datos y guarda los cambios
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('settings_blueprint.users'))

@blueprint.route('/grupos')
@login_required
def groups():
    return render_template('settings/groups.html', segment='usersSettings_groups')

@blueprint.route('/api_groups',methods=['GET'])
@login_required
def api_groups():
    grupos = Grupo.query.order_by(Grupo.id.asc()).all()
    group_schema = GroupSchema(many=True)
    return jsonify(group_schema.dump(grupos).data)

@blueprint.route('/api_groups/update', methods=['PUT'])
@login_required
def api_groups_update():
    args = {
        "nombre":request.json['nombre'],
        "descripcion":request.json['descripcion'],
        "escrito_por":current_user.id
    }
    Grupo.query.filter_by(id=request.json['id']).update(args)
    db.session.commit()
    response = {'message': f'Grupo {args["nombre"]} editado con exito.'}
    return jsonify(response)

@blueprint.route('/api_groups/insert', methods=['POST'])
@login_required
def api_groups_insert():
    group = Grupo(
        nombre=request.json['nombre'],
        descripcion=request.json['descripcion'],
        escrito_por=current_user.id
    )
    db.session.add(group)
    db.session.commit()
    response = {'message': f'Grupo {group.nombre} creado con exito.'}
    return jsonify(response)
    
@blueprint.route('/empresa')
@login_required
def company():
    empresas = Empresa.query.order_by(Empresa.id.asc()).all()
    return render_template('settings/company.html', segment='companySettings_company', empresas=empresas)

@blueprint.route('/agrega_empresa', methods=['POST','GET'])
@login_required
def add_company():
    versiones = Version.query.order_by(Version.id.asc()).all()
    if request.method == 'POST':
        activo = False
        if request.form.get('activo') =='on':
            activo=True
        company = Empresa(
            nombre=request.form.get('nombre').upper(),
            rfc=request.form.get('rfc').upper(),
            rfcProveedorSW=request.form.get('rfcProveedorSW').upper(),
            version=Version.query.filter_by(nombre=request.form.get('version')).first(),
            ftp_on=activo,
            ftp_host=request.form.get('ftp_host'),
            ftp_port=request.form.get('ftp_port'),
            ftp_username=request.form.get('ftp_username'),
            ftp_password=request.form.get('ftp_password'),
            creado_por=current_user.id
        )
        db.session.add(company)
        db.session.commit()
        return redirect(url_for('settings_blueprint.company'))
    return render_template('settings/add-company.html', segment='companySettings', versiones=versiones)

@blueprint.route('/editar_empresa/<company_id>', methods=['POST','GET'])
@login_required
def edit_company(company_id):
    company=Empresa.query.filter_by(id=company_id).first()
    versiones = Version.query.order_by(Version.id.asc()).all()
    if request.method == 'POST':
        activo = False
        if request.form.get('activo') =='on':
            activo=True
        args={
            "nombre":request.form.get('nombre').upper(),
            "rfc":request.form.get('rfc').upper(),
            "rfcProveedorSW":request.form.get('rfcProveedorSW').upper(),
            "id_version":Version.query.filter_by(nombre=request.form.get('version')).first().id,
            "ftp_on":activo,
            "ftp_host":request.form.get('ftp_host'),
            "ftp_port":request.form.get('ftp_port'),
            "ftp_username":request.form.get('ftp_username'),
            "ftp_password":request.form.get('ftp_password'),
            "escrito_por":current_user.id
        }
        Empresa.query.filter_by(id=company_id).update(args)
        db.session.commit()
        return redirect(url_for('settings_blueprint.company'))
    return render_template('settings/edit-company.html',segment='companySettings', company=company, versiones=versiones)


@blueprint.route('/tanques')
@login_required
def tanks():
    tanques = Tanques.query.all()
    return render_template('settings/tanks.html', segment='stationSettings_tanks', tanques=tanques)

@blueprint.route('/agrega_tanque', methods=['POST','GET'])
@login_required
def add_tanks():
    tanques = Tanques()
    form = TanquesForm(obj=tanques)
    form.id_estacion.choices = [(e.id, e.nombre) for e in Estacion.query.order_by('nombre').all()]
    form.id_producto.choices = [(p.id, p.nombre) for p in Producto.query.order_by('nombre').all()]
    if request.method == 'POST' and form.validate_on_submit():
        try:
            tanques.id_estacion = form.id_estacion.data[0]
            tanques.id_producto = form.id_producto.data[0]
            tanques.no_tanque = form.no_tanque.data
            tanques.volumenUtil = form.volumenUtil.data
            tanques.volumenFondaje = form.volumenFondaje.data
            tanques.volumenAgua = form.volumenAgua.data
            tanques.volumenDisponible = form.volumenDisponible.data
            tanques.volumenExtraccion = form.volumenExtraccion.data
            tanques.volumenRecepcion = form.volumenRecepcion.data
            tanques.temperatura = form.temperatura.data
            tanques.activo = form.activo.data
            tanques.creado_por = current_user.id
            db.session.add(tanques)
            db.session.commit()
            flash("Tipo creado correctamente.",'success')
        except Exception as e:
            print(e)
            flash('Error al agregar objeto: ' + str(e), 'error')
            db.session.rollback()
        return redirect(url_for('settings_blueprint.tanks')) 
    else:
        print(form.errors)
    return render_template('settings/add-tanks.html', segment='stationSettings_tanks', form=form)
    
@blueprint.route('/editar_tanque/<int:id_tanque>', methods=['POST','GET'])
@login_required
def edit_tank(id_tanque):
    return redirect(url_for('settings_blueprint.tanks'))    

@blueprint.route('/productos')
@login_required
def products():
    productos = Producto.query.all()
    return render_template('settings/products.html', segment='stationSettings_products', productos=productos)

@blueprint.route('/agregar_producto')
@login_required
def add_product():
    productos = Producto.query.all()
    form = ProductosForm(obj=productos)
    if request.method == 'POST' and form.validate_on_submit():
        try:
            form.populate_obj(productos)
            db.session.commit()
            flash("Producto actualizado correctamente.",'success')
            return redirect(url_for('settings_blueprint.products'))
        except Exception as e:
            flash('Error al agregar objeto: ' + str(e), 'error')
            db.session.rollback()
    return render_template('settings/add-product.html', segment='stationSettings_products', form=form)

@blueprint.route('editar_producto/<id_producto>', methods=['POST', 'GET'])
@login_required
def edit_product(id_producto):
    producto = Producto.query.filter_by(id=id_producto).first()
    form = ProductosForm(obj=producto)
    print(form.validate_on_submit())
    if request.method == 'POST' and form.validate_on_submit():
        try:
            form.populate_obj(producto)
            db.session.commit()

website/templates/settings/add-group.html
{% extends "index.html" %}

{% block title %}Nuevo grupo{% endblock %}

{% block main_content %}
<div class="main-groups">
    <div class="edit-group">
        <form class="form-edit-group" method="POST">
            <div class="element">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" id="nombre" placeholder="Nombre" required="true" autocomplete="off" autofocus="true"/>
            </div>
            <div class="element">
                <label for="descripcion">Descripcion</label>
                <input type="text" name="descripcion" id="descripcion" placeholder="Descripción" required="true" autocomplete="off" />
            </div>
            <div class="element">
                <button class="btn-main">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000">
                        <path d="M0 0h24v24H0V0z" fill="none"/>
                        <path d="M17.59 3.59c-.38-.38-.89-.59-1.42-.59H5c-1.11 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 
                        2-2V7.83c0-.53-.21-1.04-.59-1.41l-2.82-2.83zM12 19c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 
                        3-3 3zm1-10H7c-1.1 0-2-.9-2-2s.9-2 2-2h6c1.1 0 2 .9 2 2s-.9 2-2 2z"/>
                    </svg>
                    <span>Guardar</span>
                </button>
            </div>
            <div class="edit-group-footer">
                
            </div>
        </form>
    </div>
</div>
{% endblock %}

website/templates/settings/company.html
{% extends "layouts/base.html" %}

{% block title %} Empresa {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %}sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Empresas</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Dashboard</a></li>
              <li class="breadcrumb-item active">Empresas</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listado de empresas</h3>
                <div style="float: right;">
                  <button class="btn btn-primary"
                    type="button" onclick="window.location.href='{{ url_for( 'settings_blueprint.add_company' ) }}';">
                    <i class="fas fa-plus"></i>
                    Agregar Empresa
                  </button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="stations" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Empresa</th>
                    <th>RFC</th>
                    <th>SFTP Activo</th>
                    <th>Editar</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for empresa in empresas %}
                    <tr>
                      <td> {{ empresa.nombre}} </td>
                      <td>{{ empresa.rfc}}</td>
                      <td style="text-align: center;">
                        {% if empresa.ftp_on %}
                        <i class="fas fa-thumbs-up"></i>
                        {% else %}
                        <i class="fas fa-thumbs-down"></i>
                        {% endif %}
                      </td>
                      <td style="text-align: center;"><a href="{{url_for('settings_blueprint.edit_company', company_id=empresa.id)}}"><i class="far fa-edit"></i></a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                  <!--<tfoot>
                  <tr>
                    <th>Rendering engine</th>
                    <th>Browser</th>
                    <th>Platform(s)</th>
                    <th>Engine version</th>
                    <th>CSS grade</th>
                  </tr>
                  </tfoot>-->
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}


{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>

  <!-- page script -->
  <script>
    $(function () {
      $("#stations").DataTable({
        "responsive": true,
        "autoWidth": false,
        
      });
     
    });
  </script>

{% endblock javascripts %}

website/templates/settings/edit-group.html
{% extends "index.html" %}

{% block title %}Ediar grupo{% endblock %}

{% block main_content %}
<div class="main-groups">
    <div class="edit-group">
        <form class="form-edit-group" method="POST">
            <div class="element">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" id="nombre" placeholder="nombre" required="true" autocomplete="off" readonly value="{{ data.grupo.nombre }}" />
            </div>
            <div class="element">
                <label for="descripcion">Descripcion</label>
                <input type="text" name="descripcion" id="descripcion" placeholder="descripcion" required="true" autocomplete="off" value="{{ data.grupo.descripcion }}" autofocus="true"/>
            </div>
            <div class="element">
                <button class="btn-main">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000">
                        <path d="M0 0h24v24H0V0z" fill="none"/>
                        <path d="M17.59 3.59c-.38-.38-.89-.59-1.42-.59H5c-1.11 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 
                        2-2V7.83c0-.53-.21-1.04-.59-1.41l-2.82-2.83zM12 19c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 
                        3-3 3zm1-10H7c-1.1 0-2-.9-2-2s.9-2 2-2h6c1.1 0 2 .9 2 2s-.9 2-2 2z"/>
                    </svg>
                    <span>Guardar</span>
                </button>
            </div>
            <div class="edit-group-footer">
                <p>Ultima modificación realiza fue hecha por <span class="bolder">{{ data.grupo.escrito_por }}</span> el dia <span class="bolder">{{ data.grupo.escrito_en }}</span></p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

website/templates/settings/products.html
{% extends "layouts/base.html" %}

{% block title %} Productos {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed{% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">
  <!--Toastr-->
  <link rel="stylesheet" href="{{url_for('static', filename='assets/plugins/toastr/toastr.min.css')}}">
{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Productos</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{url_for('home_blueprint.index')}}">Dashboard</a></li>
              <li class="breadcrumb-item active">Productos</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listado de productos</h3>
                <div style="float: right;">
                  <button class="btn btn-primary"
                    type="button" onclick="window.location.href='{{ url_for( 'settings_blueprint.add_product' ) }}';">
                    <i class="fas fa-plus"></i>
                    Agregar Producto
                  </button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="products" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Clave</th>
                    <th>Octanaje</th>
                    <th>Editar</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for producto in productos %}
                  <tr>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.claveProducto }}</td>
                    <td>{{ producto.composicionOctanajeDeGasolina }}</td>
                    <td style="text-align: center;"><a href="{{url_for('settings_blueprint.edit_product', id_producto=producto.id)}}"><i class="far fa-edit"></i></a></td>
                  </tr>
                  {% endfor %}
                  </tbody>
                  <!--<tfoot>
                  <tr>
                    <th>Rendering engine</th>
                    <th>Browser</th>
                    <th>Platform(s)</th>
                    <th>Engine version</th>
                    <th>CSS grade</th>
                  </tr>
                  </tfoot>-->
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}


{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!--Toastr-->
  <script src="/static/assets/plugins/toastr/toastr.min.js"></script>
  <!-- page script -->
  <script>
    $(function () {
      $("#products").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
     
    });
  </script>
  <script>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          toastr.{{ category }}('{{ message }}');
        {% endfor %}
      {% endif %}
    {% endwith %}
  </script>

{% endblock javascripts %}